# Site
repository: stefanagapie/modern-resume-theme
favicon: images/favicon.ico

# Personal info
name: Samaneh Ghafouri
title: Front-End Engineer
email: samaneh2010gh@gmail.com
website: https://samanehghafouri.github.io/


# Social links
#twitter_username: jekyll
github_username:  SamanehGhafouri
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: samaneh.ghafouri90
linkedin_username: samaneh-ghafouri-b62847145
# pinterest_username: jekyll
#youtube_username: jekyll
# googleplus_username: +jekyll

# About Section
# about_title: About me
about_profile_image: images/sam-pic.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello, my name's Samaneh, an energetic web developer whose goal is to begin my advanture in software engineering.
  I am an ambitious, and have the drive and energy needed to make a difference to a project. I am looking for an
  entry level position with an exciting company that is building amazing products.

  I am most skilled in: <mark>Angular</mark> , <mark>Meteor</mark> , and <mark>Python</mark>

# Projects Section
#projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
educaton_title: Education & Experience

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Languages:
   - English(Proficient)
   - Persian(native)
   - Arabic(Basic)
   - Turkish(Basic)


#Alongside my interests in software engineering some of my other interests and hobbies are

# Footer
footer_show_references: true

# Build settings
remote_theme: stefanagapie/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
